### ISSUE TITLE
APU header missing in OID4VP response

### ISSUE THREAD

**Issue by thomasnymand** [eu-digital-identity-wallet/eudi-lib-ios-wallet-kit#104]
Hi,

Seems as if this change left out the "apu" header necessary for validating the document signature at verifier? Is this header available somewhere else in the response?

Br,
Thomas Nymand

 _Originally posted by @thomasnymand in [b97c79a](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit/commit/b97c79a98aecfb63a8a1bfcad781e5580470b0ad#r147691027)_

**Comment by phisakel** [comment]
Hi, the header is now again present in the response. Tag v0.7.0

**Comment by thomasnymand** [comment]
Perfect, thanks :)
