### ISSUE TITLE
OpenID4VP - Input Descriptor Constraints

### ISSUE THREAD

**Issue by icarboneaq** [eu-digital-identity-wallet/eudi-lib-ios-wallet-kit#118]
I'm attempting to build something that has an enhanced presentation experience, and was hoping to gain access to the optionality of the input descriptor constraints. It looks like the optional parameters in the Input Descriptors part of the presentation definition is parsed out [here](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-presentation-exchange-swift/blob/4e1ac57b6772f7f6eac5ef24d977c42e94bc6565/Sources/PresentationDefinition/Field.swift#L24), but isn't propagated out as a requested item [here](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit/blob/d745d4f00be8d81e790e9f7b6460dad09ede5b0c/Sources/EudiWalletKit/Services/OpenId4VpService.swift#L95). Is there any intent to pass that information up? Alternatively, would it be possible to make [this](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit/blob/d745d4f00be8d81e790e9f7b6460dad09ede5b0c/Sources/EudiWalletKit/Services/OpenId4VpService.swift#L41) public so that we can access other information about the presentation?

**Comment by phisakel** [comment]
Hi @icarboneaq. Please check release [0.7.7](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit/releases/tag/v0.7.7) and [0.7.8](https://github.com/eu-digital-identity-wallet/eudi-lib-ios-wallet-kit/releases/tag/v0.7.8). Requested information has been added.
