### ISSUE TITLE
Missing repo

### ISSUE THREAD

**Issue by johan-sellstrom** [eu-digital-identity-wallet/eudi-lib-ios-wallet-kit#24]
`github.com: https://github.com/eu-digital-identity-wallet/eudi-lib-ios-openid4vci-swift.git: The remote repository could not be accessed. Make sure a valid repository exists at the specified location and that the correct credentials have been supplied.
`

**Comment by mgiakkou** [comment]
Repos are verified to be public. The issue existed during the process of publication.
