### ISSUE TITLE
Cross-platform reference implementation

### ISSUE THREAD

**Issue by DJHunn39** [eu-digital-identity-wallet/eudi-lib-ios-wallet-kit#26]
As mentioned on the EUDI Wallet Reference Implementation webinar hosted by the Open Wallet Foundation, there was a question regarding whether or not the implementation is planned to add libraries enabling cross-platform app developers to easily consume packages such as this wallet kit (and the Android wallet core) without needing to write their own bridging code.

For example, if a dev wanted to build a EUDIW app using react-native for the UI (or Flutter, .NET MAUI, Ionic, etc.), they would need to develop a package containing native Swift/Kotlin -> JS bridges in order to access the capabilities of this kit. As a predominantly JS developer myself, it's difficult to use the reference implementation as is.

In an ideal world, to encourage wider adoption of the reference implementation across multiple tech stacks, such packages would be a part of the reference implementation itself.

I understand from the response in the webinar that this is something that could be looked at, but isn't planned in the short term - this issue could serve as a starting point for discussion of the idea.

**Comment by AlexanderShenshin** [comment]
For anyone who interested in using EUDI reference implementation for cross-platform dev, please take a look at [EUDI Wallet Kit React Native](https://github.com/openwallet-foundation-labs/eudi-wallet-kit-react-native) project hosted by OpenWallet Foundation Labs (please note that it's not production ready yet).

The project is essentially a React Native library that provides JS API for EUDI reference implementation (using platform specific native modules and React Native Bridge).

**Comment by mgiakkou** [comment]
Dear Danny,

Thank you for your contribution. Unfortunately, the cross-platform support is not currently in our roadmap for the coming releases. Please stay tuned for further infomration on that.

Thank you,
Michalis.

**Comment by mgiakkou** [comment]
Dear Danny,

The cross-platform support is not yet in our roadmap for the coming releases. You can find our roadmap publicly available on https://github.com/orgs/eu-digital-identity-wallet/projects/24 where it will be added if suitable.

Thank you,
Michalis.
