### ISSUE TITLE
Return the QR code in a string representation to device engagement

### ISSUE THREAD

**Issue by akarabashov** [eu-digital-identity-wallet/eudi-lib-ios-wallet-kit#41]
The current implementation of the library returns a QR code as a PNG image to device engagement. I suggest that the library return a string value instead. This change would increase flexibility, allowing users to generate QR images with the desired logos and resolution, or use the string in other ways. It would also make the API more consistent, since the Android library already returns a string for device engagement.

**Comment by phisakel** [comment]
Change included in main branch and tag 0.3.7
