### ISSUE TITLE
Error 3 on iOS when invoking issueDocumentsByOfferUrl with userAuthenticationRequired enabled

### ISSUE THREAD

**Issue by kimera84** [eu-digital-identity-wallet/eudi-lib-ios-wallet-kit#84]
Hello,

We are encountering an issue on iOS when attempting to invoke the issueDocumentsByOfferUrl method from the EudiWalletKit SDK. The problem occurs specifically when userAuthenticationRequired is set to true, whether using biometric authentication (Face ID) or passcode. The error message returned is:

`Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state.}`

It does not occur when userAuthenticationRequired is set to false

**PS.** is this url: [https://dev.issuer.eudiw.dev/credential_offer_choice](url) valid to issue Pre-auth credentials? It worked till yesterday, now not anymore.

Thank you 
Sergio

**Comment by phisakel** [comment]
@kimera84 Thanks for the issue, it is fixed in tag v0.6.3
