### ISSUE TITLE
Undefined error while calling issueDocumentsByOfferUrl() method

### ISSUE THREAD

**Issue by josmilan** [eu-digital-identity-wallet/eudi-lib-ios-wallet-kit#94]
```func issueDoc(qrCode: String) async{
    if let wallet = try? EudiWallet(openID4VciIssuerUrl: "https://eudi.netcompany-intrasoft.com/pid-issuer", openID4VciConfig: .init(clientId: "wallet-dev", authFlowRedirectionURI: URL(string: "eudi-openid4ci://authorize/")!)){
      let offer = try? await wallet.resolveOfferUrlDocTypes(uriOffer: qrCode)
      if let docModel = offer?.docModels{
        do{
          let documets = try await wallet.issueDocumentsByOfferUrl(offerUri: qrCode, docTypes: docModel)
          print(documets.first?.docType)
        }
        catch{
          print("Error")
        }
      }
    }
  }
```

I have implemented the above code to initialise and issue an mDoc credential from the test server https://issuer-backend.eudiw.dev/ which issued a credential offer: openid-credential-offer://?credential_offer=%7B%22credential_issuer%22%3A%22https%3A%2F%[2Fissuer-backend.eudiw.dev](http://2fissuer-backend.eudiw.dev/)%22%2C%22credential_configuration_ids%22%3A%5B%[22eu.europa.ec](http://22eu.europa.ec/).eudi.pid_mso_mdoc%22%5D%2C%22grants%22%3A%7B%22authorization_code%22%3A%7B%22authorization_server%22%3A%22https%3A%2F%[2Fauth.eudiw.dev](http://2fauth.eudiw.dev/)%2Frealms%2Fpid-issuer-realm%22%7D%7D%7D.
While calling issueDocumentsByOfferUrl() method it returns undefined error.

**Comment by josmilan** [comment]
Hi Any update on this

**Comment by phisakel** [comment]
Hi please use "https://dev.issuer.eudiw.dev" for the openID4VciIssuerUrl parameter
